export default JSON.parse(`[
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150011",
    "Codigo Municipio": "11",
    "Denominacion": "Abegondo",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "San Marco (Abegondo) (Santaia)",
    "Habitantes": "5709",
    "Superficie": "83,81",
    "Densidad": "68,1"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150026",
    "Codigo Municipio": "26",
    "Denominacion": "Ames",
    "Fecha de inscripción": "1986-12-10",
    "Capitalidad": "Bertamiráns (Ortoño) (San Xoán)",
    "Habitantes": "29331",
    "Superficie": "80,04",
    "Densidad": "366,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150032",
    "Codigo Municipio": "32",
    "Denominacion": "Aranga",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Ponte Aranga (Aranga) (San Paio)",
    "Habitantes": "2072",
    "Superficie": "119,65",
    "Densidad": "17,3"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150047",
    "Codigo Municipio": "47",
    "Denominacion": "Ares",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Ares (Ares) (San Xosé)",
    "Habitantes": "5839",
    "Superficie": "18,31",
    "Densidad": "318,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150050",
    "Codigo Municipio": "50",
    "Denominacion": "Arteixo",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Baiuca, A (Arteixo) (Santiago)",
    "Habitantes": "30725",
    "Superficie": "93,68",
    "Densidad": "327,9"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150063",
    "Codigo Municipio": "63",
    "Denominacion": "Arzúa",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Arzúa (Arzúa) (Santiago)",
    "Habitantes": "6315",
    "Superficie": "155,48",
    "Densidad": "40,6"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150079",
    "Codigo Municipio": "79",
    "Denominacion": "Baña, A",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "San Vicenzo (A Baña) (San Vicenzo)",
    "Habitantes": "3967",
    "Superficie": "98,19",
    "Densidad": "40,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150085",
    "Codigo Municipio": "85",
    "Denominacion": "Bergondo",
    "Fecha de inscripción": "1987-03-12",
    "Capitalidad": "Carrio (Bergondo) (San Salvador)",
    "Habitantes": "6712",
    "Superficie": "32,72",
    "Densidad": "205,1"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150098",
    "Codigo Municipio": "98",
    "Denominacion": "Betanzos",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Betanzos",
    "Habitantes": "13565",
    "Superficie": "24,19",
    "Densidad": "560,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150102",
    "Codigo Municipio": "102",
    "Denominacion": "Boimorto",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Gándara, A (Boimorto) (Santiago)",
    "Habitantes": "2200",
    "Superficie": "82,34",
    "Densidad": "26,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150119",
    "Codigo Municipio": "119",
    "Denominacion": "Boiro",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Boiro de Arriba (Boiro) (Santa Baia)",
    "Habitantes": "19165",
    "Superficie": "86,58",
    "Densidad": "221,3"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150124",
    "Codigo Municipio": "124",
    "Denominacion": "Boqueixón",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Forte, O (Boqueixón) (San Vicente)",
    "Habitantes": "4417",
    "Superficie": "73,18",
    "Densidad": "60,3"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150130",
    "Codigo Municipio": "130",
    "Denominacion": "Brión",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Pedrouzos (Brión) (San Fins)",
    "Habitantes": "7369",
    "Superficie": "74,9",
    "Densidad": "98,3"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150145",
    "Codigo Municipio": "145",
    "Denominacion": "Cabana de Bergantiños",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Carballa, A (Cesullas) (Santo Estevo)",
    "Habitantes": "4759",
    "Superficie": "100,23",
    "Densidad": "47,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150158",
    "Codigo Municipio": "158",
    "Denominacion": "Cabanas",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Cabanas (Cabanas) (Santo André)",
    "Habitantes": "3299",
    "Superficie": "30,3",
    "Densidad": "108,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150161",
    "Codigo Municipio": "161",
    "Denominacion": "Camariñas",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Camariñas (Camariñas) (San Xurxo)",
    "Habitantes": "6082",
    "Superficie": "51,6",
    "Densidad": "117,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150177",
    "Codigo Municipio": "177",
    "Denominacion": "Cambre",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Cambre (Cambre) (Santa María)",
    "Habitantes": "23879",
    "Superficie": "40,74",
    "Densidad": "586,1"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150183",
    "Codigo Municipio": "183",
    "Denominacion": "Capela, A",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Neves, As (A Capela) (Santiago)",
    "Habitantes": "1376",
    "Superficie": "58",
    "Densidad": "23,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150196",
    "Codigo Municipio": "196",
    "Denominacion": "Carballo",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Carballo (Carballo) (San Xoán)",
    "Habitantes": "31358",
    "Superficie": "186,09",
    "Densidad": "168,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1159012",
    "Codigo Municipio": "9012",
    "Denominacion": "Cariño",
    "Fecha de inscripción": "1988-05-12",
    "Capitalidad": "Cariño (Cariño) (San Bartolomeu)",
    "Habitantes": "4373",
    "Superficie": "47,19",
    "Densidad": "92,6"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150200",
    "Codigo Municipio": "200",
    "Denominacion": "Carnota",
    "Fecha de inscripción": "1986-12-09",
    "Capitalidad": "Carnota (Santa Comba de Carnota) (Santa Comba)",
    "Habitantes": "4605",
    "Superficie": "70,9",
    "Densidad": "64,9"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150217",
    "Codigo Municipio": "217",
    "Denominacion": "Carral",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Carral (Paleo) (Santo Estevo)",
    "Habitantes": "6130",
    "Superficie": "48,03",
    "Densidad": "127,6"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150222",
    "Codigo Municipio": "222",
    "Denominacion": "Cedeira",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Cedeira (Cedeira) (Santa María do Mar)",
    "Habitantes": "7254",
    "Superficie": "46,2",
    "Densidad": "157,0"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150238",
    "Codigo Municipio": "238",
    "Denominacion": "Cee",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Cee (Cee) (Santa María)",
    "Habitantes": "7855",
    "Superficie": "57,45",
    "Densidad": "136,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150243",
    "Codigo Municipio": "243",
    "Denominacion": "Cerceda",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Campo da Feira, O (Cerceda) (San Martiño)",
    "Habitantes": "5318",
    "Superficie": "111,27",
    "Densidad": "47,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150256",
    "Codigo Municipio": "256",
    "Denominacion": "Cerdido",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Vila da Igrexa, A (Cerdido) (San Martiño)",
    "Habitantes": "1312",
    "Superficie": "52,72",
    "Densidad": "24,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150269",
    "Codigo Municipio": "269",
    "Denominacion": "Cesuras",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Cesuras (Dordaño) (Santa María)",
    "Habitantes": "2174",
    "Superficie": "79,46",
    "Densidad": "27,3"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150275",
    "Codigo Municipio": "275",
    "Denominacion": "Coirós",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Coirós de Arriba (Coirós) (San Xulián)",
    "Habitantes": "1765",
    "Superficie": "33,87",
    "Densidad": "52,1"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150281",
    "Codigo Municipio": "281",
    "Denominacion": "Corcubión",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Corcubión (Corcubión) (San Marcos)",
    "Habitantes": "1731",
    "Superficie": "6,52",
    "Densidad": "265,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150294",
    "Codigo Municipio": "294",
    "Denominacion": "Coristanco",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "San Roque (Traba) (Santa María)",
    "Habitantes": "6974",
    "Superficie": "141,28",
    "Densidad": "49,3"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150308",
    "Codigo Municipio": "308",
    "Denominacion": "Coruña, A",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Coruña, A",
    "Habitantes": "246146",
    "Superficie": "37,83",
    "Densidad": "6506,6"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150315",
    "Codigo Municipio": "315",
    "Denominacion": "Culleredo",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Tarrío (Culleredo) (Santo Estevo)",
    "Habitantes": "29416",
    "Superficie": "61,73",
    "Densidad": "476,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150320",
    "Codigo Municipio": "320",
    "Denominacion": "Curtis",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Teixeiro (Curtis) (Santaia)",
    "Habitantes": "4159",
    "Superficie": "116,57",
    "Densidad": "35,6"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150336",
    "Codigo Municipio": "336",
    "Denominacion": "Dodro",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Tallós (Laíño) (San Xián)",
    "Habitantes": "2977",
    "Superficie": "36,12",
    "Densidad": "82,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150341",
    "Codigo Municipio": "341",
    "Denominacion": "Dumbría",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Dumbría (Dumbría) (Santa Baia)",
    "Habitantes": "3291",
    "Superficie": "125,19",
    "Densidad": "26,2"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150354",
    "Codigo Municipio": "354",
    "Denominacion": "Fene",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Fene (Fene) (San Salvador)",
    "Habitantes": "13780",
    "Superficie": "26,31",
    "Densidad": "523,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150367",
    "Codigo Municipio": "367",
    "Denominacion": "Ferrol",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Ferrol (Ferrol)",
    "Habitantes": "71997",
    "Superficie": "82,65",
    "Densidad": "871,1"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150373",
    "Codigo Municipio": "373",
    "Denominacion": "Fisterra",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Fisterra (Fisterra) (Santa María)",
    "Habitantes": "4990",
    "Superficie": "29,43",
    "Densidad": "169,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150389",
    "Codigo Municipio": "389",
    "Denominacion": "Frades",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Cimadevila (Frades) (San Martiño)",
    "Habitantes": "2566",
    "Superficie": "81,56",
    "Densidad": "31,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150392",
    "Codigo Municipio": "392",
    "Denominacion": "Irixoa",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Pazo de Irixoa, O (Irixoa) (San Lourenzo)",
    "Habitantes": "1492",
    "Superficie": "68,59",
    "Densidad": "21,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150413",
    "Codigo Municipio": "413",
    "Denominacion": "Laracha, A",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Laracha, A (Torás) (Santa María)",
    "Habitantes": "11367",
    "Superficie": "125,95",
    "Densidad": "90,2"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150406",
    "Codigo Municipio": "406",
    "Denominacion": "Laxe",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Laxe (Laxe) (Santa María)",
    "Habitantes": "3313",
    "Superficie": "36,78",
    "Densidad": "90,0"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150428",
    "Codigo Municipio": "428",
    "Denominacion": "Lousame",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Portobravo (Lousame) (San Xoán)",
    "Habitantes": "3621",
    "Superficie": "93,65",
    "Densidad": "38,6"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150434",
    "Codigo Municipio": "434",
    "Denominacion": "Malpica de Bergantiños",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Malpica (Malpica de Bergantiños) (San Xulián)",
    "Habitantes": "5998",
    "Superficie": "61,22",
    "Densidad": "97,9"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150449",
    "Codigo Municipio": "449",
    "Denominacion": "Mañón",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Caión (Mañón) (Santa María)",
    "Habitantes": "1537",
    "Superficie": "82,21",
    "Densidad": "18,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150452",
    "Codigo Municipio": "452",
    "Denominacion": "Mazaricos",
    "Fecha de inscripción": "1986-12-15",
    "Capitalidad": "Picota, A (Mazaricos) (San Xoán)",
    "Habitantes": "4533",
    "Superficie": "187,3",
    "Densidad": "24,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150465",
    "Codigo Municipio": "465",
    "Denominacion": "Melide",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Melide (Melide) (San Pedro)",
    "Habitantes": "7502",
    "Superficie": "101,3",
    "Densidad": "74,0"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150471",
    "Codigo Municipio": "471",
    "Denominacion": "Mesía",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Pobra, A (Bascoi) (Santiago)",
    "Habitantes": "2879",
    "Superficie": "107,07",
    "Densidad": "26,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150487",
    "Codigo Municipio": "487",
    "Denominacion": "Miño",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Carreira, A (Miño) (Santa María)",
    "Habitantes": "5739",
    "Superficie": "32,97",
    "Densidad": "174,0"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150490",
    "Codigo Municipio": "490",
    "Denominacion": "Moeche",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "San Ramón (San Xoán de Moeche) (San Xoán)",
    "Habitantes": "1358",
    "Superficie": "48,5",
    "Densidad": "2"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150503",
    "Codigo Municipio": "503",
    "Denominacion": "Monfero",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Rebordelo (San Fiz de Monfero) (San Fiz)",
    "Habitantes": "2129",
    "Superficie": "171,67",
    "Densidad": "12,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150510",
    "Codigo Municipio": "510",
    "Denominacion": "Mugardos",
    "Fecha de inscripción": "1987-12-22",
    "Capitalidad": "Mugardos (Mugardos) (San Xulián)",
    "Habitantes": "5456",
    "Superficie": "12,77",
    "Densidad": "427,2"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150531",
    "Codigo Municipio": "531",
    "Denominacion": "Muros",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Muros (Muros) (San Pedro)",
    "Habitantes": "9437",
    "Superficie": "72,91",
    "Densidad": "129,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150525",
    "Codigo Municipio": "525",
    "Denominacion": "Muxía",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Muxía (Muxía) (Santa María)",
    "Habitantes": "5269",
    "Superficie": "121,19",
    "Densidad": "43,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150546",
    "Codigo Municipio": "546",
    "Denominacion": "Narón",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Narón",
    "Habitantes": "39238",
    "Superficie": "66,91",
    "Densidad": "586,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150559",
    "Codigo Municipio": "559",
    "Denominacion": "Neda",
    "Fecha de inscripción": "1986-09-19",
    "Capitalidad": "Neda (Neda) (San Nicolás)",
    "Habitantes": "5422",
    "Superficie": "24,46",
    "Densidad": "221,6"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150562",
    "Codigo Municipio": "562",
    "Denominacion": "Negreira",
    "Fecha de inscripción": "1987-11-20",
    "Capitalidad": "Negreira (Negreira) (San Xián)",
    "Habitantes": "7079",
    "Superficie": "115,1",
    "Densidad": "61,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150578",
    "Codigo Municipio": "578",
    "Denominacion": "Noia",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Noia (Noia) (San Martiño)",
    "Habitantes": "14757",
    "Superficie": "37,21",
    "Densidad": "396,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150584",
    "Codigo Municipio": "584",
    "Denominacion": "Oleiros",
    "Fecha de inscripción": "1986-10-21",
    "Capitalidad": "Real, O (Oleiros) (Santa María)",
    "Habitantes": "34386",
    "Superficie": "43,66",
    "Densidad": "787,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150597",
    "Codigo Municipio": "597",
    "Denominacion": "Ordes",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Ordes (Ordes) (Santa María)",
    "Habitantes": "12963",
    "Superficie": "157,23",
    "Densidad": "82,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150601",
    "Codigo Municipio": "601",
    "Denominacion": "Oroso",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Sigüeiro (Oroso) (San Martiño)",
    "Habitantes": "7328",
    "Superficie": "72,59",
    "Densidad": "100,9"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150618",
    "Codigo Municipio": "618",
    "Denominacion": "Ortigueira",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Ortigueira (Ortigueira) (Santa Marta)",
    "Habitantes": "6550",
    "Superficie": "209,6",
    "Densidad": "31,2"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150623",
    "Codigo Municipio": "623",
    "Denominacion": "Outes",
    "Fecha de inscripción": "1986-10-08",
    "Capitalidad": "Serra de Outes, A (Outes) (San Pedro)",
    "Habitantes": "7192",
    "Superficie": "99,74",
    "Densidad": "72,1"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150639",
    "Codigo Municipio": "639",
    "Denominacion": "Oza dos Ríos",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Oza (Oza) (San Pedro)",
    "Habitantes": "3227",
    "Superficie": "72,14",
    "Densidad": "44,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150644",
    "Codigo Municipio": "644",
    "Denominacion": "Paderne",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Consistorio, O (Paderne) (San Xoán)",
    "Habitantes": "2597",
    "Superficie": "39,83",
    "Densidad": "65,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150657",
    "Codigo Municipio": "657",
    "Denominacion": "Padrón",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Padrón (Padrón) (Santiago)",
    "Habitantes": "8882",
    "Superficie": "48,37",
    "Densidad": "183,6"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150660",
    "Codigo Municipio": "660",
    "Denominacion": "Pino, O",
    "Fecha de inscripción": "1986-09-03",
    "Capitalidad": "Pedrouzo, O (Arca) (Santaia)",
    "Habitantes": "4732",
    "Superficie": "132,15",
    "Densidad": "35,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150676",
    "Codigo Municipio": "676",
    "Denominacion": "Pobra do Caramiñal, A",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Pobra do Caramiñal, A (O Caramiñal) (Santa María a Antiga)",
    "Habitantes": "9664",
    "Superficie": "32,51",
    "Densidad": "297,2"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150682",
    "Codigo Municipio": "682",
    "Denominacion": "Ponteceso",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Ponteceso (Cospindo) (San Tirso)",
    "Habitantes": "6065",
    "Superficie": "91,97",
    "Densidad": "65,9"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150695",
    "Codigo Municipio": "695",
    "Denominacion": "Pontedeume",
    "Fecha de inscripción": "1986-10-21",
    "Capitalidad": "Pontedeume (Pontedeume) (Santiago)",
    "Habitantes": "8324",
    "Superficie": "29,26",
    "Densidad": "284,4"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150709",
    "Codigo Municipio": "709",
    "Denominacion": "Pontes de García Rodríguez, As",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Pontes de García Rodríguez, As (As Pontes de García Rodríguez) (Santa María)",
    "Habitantes": "10996",
    "Superficie": "249,37",
    "Densidad": "44,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150716",
    "Codigo Municipio": "716",
    "Denominacion": "Porto do Son",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Porto do Son (Noal) (San Vicente)",
    "Habitantes": "9699",
    "Superficie": "94,58",
    "Densidad": "102,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150721",
    "Codigo Municipio": "721",
    "Denominacion": "Rianxo",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Rianxo (Rianxo) (Santa Comba)",
    "Habitantes": "11729",
    "Superficie": "58,79",
    "Densidad": "199,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150737",
    "Codigo Municipio": "737",
    "Denominacion": "Ribeira",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Santa Uxía de Ribeira (Ribeira) (Santa Uxía)",
    "Habitantes": "27778",
    "Superficie": "68,83",
    "Densidad": "403,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150742",
    "Codigo Municipio": "742",
    "Denominacion": "Rois",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Dices, Os (Rois) (San Mamede)",
    "Habitantes": "4871",
    "Superficie": "92,76",
    "Densidad": "52,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150755",
    "Codigo Municipio": "755",
    "Denominacion": "Sada",
    "Fecha de inscripción": "1987-03-02",
    "Capitalidad": "Sada (Sada) (Santa María)",
    "Habitantes": "14922",
    "Superficie": "27,49",
    "Densidad": "542,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150768",
    "Codigo Municipio": "768",
    "Denominacion": "San Sadurniño",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Avenida do Marqués de Figueroa (San Sadurniño) (Santa María)",
    "Habitantes": "3061",
    "Superficie": "98,98",
    "Densidad": "30,9"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150774",
    "Codigo Municipio": "774",
    "Denominacion": "Santa Comba",
    "Fecha de inscripción": "1986-12-12",
    "Capitalidad": "Santa Cataliña de Armada (Santa Comba) (San Pedro)",
    "Habitantes": "10101",
    "Superficie": "203,7",
    "Densidad": "49,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150780",
    "Codigo Municipio": "780",
    "Denominacion": "Santiago de Compostela",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Santiago de Compostela",
    "Habitantes": "95671",
    "Superficie": "220,01",
    "Densidad": "434,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150793",
    "Codigo Municipio": "793",
    "Denominacion": "Santiso",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Agro do Chao (A Ponte Arcediago) (San Xoán)",
    "Habitantes": "1838",
    "Superficie": "67,39",
    "Densidad": "27,2"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150807",
    "Codigo Municipio": "807",
    "Denominacion": "Sobrado",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Sobrado (A Porta) (San Pedro)",
    "Habitantes": "2037",
    "Superficie": "120,64",
    "Densidad": "16,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150814",
    "Codigo Municipio": "814",
    "Denominacion": "Somozas, As",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Igrexa, A (As Somozas) (Santiago Seré)",
    "Habitantes": "1279",
    "Superficie": "70,91",
    "Densidad": "18,0"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150829",
    "Codigo Municipio": "829",
    "Denominacion": "Teo",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Ramallosa, A (Lucí) (Santa Mariña)",
    "Habitantes": "18454",
    "Superficie": "79,3",
    "Densidad": "232,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150835",
    "Codigo Municipio": "835",
    "Denominacion": "Toques",
    "Fecha de inscripción": "1986-09-29",
    "Capitalidad": "Souto (A Capela) (Santa María)",
    "Habitantes": "1302",
    "Superficie": "77,93",
    "Densidad": "16,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150840",
    "Codigo Municipio": "840",
    "Denominacion": "Tordoia",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Pontepedra, A (Cabaleiros) (San Xián)",
    "Habitantes": "3924",
    "Superficie": "124,55",
    "Densidad": "31,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150853",
    "Codigo Municipio": "853",
    "Denominacion": "Touro",
    "Fecha de inscripción": "1986-08-29",
    "Capitalidad": "Fonte Díaz (Touro) (San Xoán)",
    "Habitantes": "3979",
    "Superficie": "115,34",
    "Densidad": "34,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150866",
    "Codigo Municipio": "866",
    "Denominacion": "Trazo",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Viaño Pequeno (Campo) (San Xoán)",
    "Habitantes": "3433",
    "Superficie": "101,3",
    "Densidad": "33,8"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150888",
    "Codigo Municipio": "888",
    "Denominacion": "Val do Dubra",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Bembibre (Bembibre) (San Salvador)",
    "Habitantes": "4234",
    "Superficie": "108,64",
    "Densidad": "38,9"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150872",
    "Codigo Municipio": "872",
    "Denominacion": "Valdoviño",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Aviño (Valdoviño) (Santalla)",
    "Habitantes": "6857",
    "Superficie": "88,22",
    "Densidad": "77,7"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150891",
    "Codigo Municipio": "891",
    "Denominacion": "Vedra",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Avenida do Mestre Manuel Gómez Lorenzo (Vedra) (Santa Eulalia)",
    "Habitantes": "5043",
    "Superficie": "52,78",
    "Densidad": "95,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150912",
    "Codigo Municipio": "912",
    "Denominacion": "Vilarmaior",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Armada, A (Vilarmaior) (San Pedro)",
    "Habitantes": "1261",
    "Superficie": "30,35",
    "Densidad": "41,5"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150905",
    "Codigo Municipio": "905",
    "Denominacion": "Vilasantar",
    "Fecha de inscripción": "1986-10-31",
    "Capitalidad": "Ru (Vilasantar) (Santiago)",
    "Habitantes": "1368",
    "Superficie": "59,22",
    "Densidad": "23,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150927",
    "Codigo Municipio": "927",
    "Denominacion": "Vimianzo",
    "Fecha de inscripción": "1987-01-26",
    "Capitalidad": "Vimianzo (Vimianzo) (San Vicenzo)",
    "Habitantes": "7977",
    "Superficie": "187,27",
    "Densidad": "42,"
  },
  {
    "Comunidad Autónoma": "Galicia",
    "Código de CA": "12",
    "Codigo Provincia": "15",
    "Provincia": "Coruña, A",
    "Número de inscripción": "1150933",
    "Codigo Municipio": "933",
    "Denominacion": "Zas",
    "Fecha de inscripción": "1986-11-21",
    "Capitalidad": "Zas (Zas) (Santo André)",
    "Habitantes": "5109",
    "Superficie": "133,29",
    "Densidad": "38,3"
  }
]
`);