<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSya9UI5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSya9UI5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSya9UI5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSya9UI5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSya9UI5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sya9UI5',
    'container.build_id' => 'a0a17c01',
    'container.build_time' => 1677229287,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSya9UI5');
